export default {
  getListModule: [
    {
      title: "Dashboard",
      label: "DASHBOARD",
      icon: "dashboard",
      link: "/Dashboard",
    },
    {
      title: "QA Module",
      label: "ADMIN MODULE",
      icon: "assignment",
      link: "/QATable",
    },
    {
      title: "Assistant QA Module",
      label: "QA ASSISTANT MODULE",
      icon: "inventory",
      link: "/AssistantQATable",
    },
    {
      title: "Primary Module",
      label: "PRIMARY MODULE",
      icon: "list_alt",
      link: "/PrimaryTable",
    },
    {
      title: "Directors Module",
      label: "DIRECTORS MODULE",
      icon: "article",
      link: "/DirectorTable",
    },
    {
      title: "HR Module",
      label: "HR MODULE",
      icon: "chrome_reader_mode",
      link: "/HRTable",
    },
    {
      title: "Audit Module",
      label: "AUDIT MODULE",
      icon: "assessment",
      link: "/AuditTable",
    },
  ],
  // getListDefaultModule: [
  //   {
  //     title: "DASHBOARD",
  //     label: "DASHBOARD",
  //     icon: "dashboard",
  //     link: "/Dashboard",
  //   },
  //   {
  //     title: "REPORT MODULE",
  //     label: "REPORT MODULE",
  //     icon: "summarize",
  //     link: "#/ReportTable",
  //   },
  // ],

  getAccessModule: [],
  getGoogleUser: [],
  getDash: [],
  getList: [],
  getDirector: [],
  getAssistantQA: [],
  getAssistantQAForm: [],
  getAssistantSubCode: [],
  getAssistantDivision: [],
  getCountSubs: [],
  getEmployee: [],
  getIRForm: [],
  getQAForm: [],
  getQACon: [],
  getQA: [],
  getHR: [],
  getHead: [],
  getRiskUni: [],
  getcorrective: [],
  // getpreventive: [],
  getRiskData: [],
  getRemarks: [],
  getForm: [],
  getDiv: [],
  getArea: [],
  getAccess: [],
  getAudit: [],
  getSubject: [],
  getAllRisk: [],
  getPrimary: [],
  getActionItem: [],
  getAPAction: [],
  getQAAction: [],
  getReturnAction: [],
  getReturnReviewAction: [],
  getRCA: [],
  getReturnRCA: [],
  getReturnReviewRCA: [],
  getSecondary: [],
  getRisk: [],
  getRiskChild: [],
  getUser: [],
  user: null,
  departments: [],
  deptList: [],
  subjectcategory: [],
  subjectname: [],
  division: [],
  employees: [],
  demerit: [],
};
